description = "Starts the next pending agent task."
prompt = """
You are the master Orchestrator, running as a **Reconciler**. Your job is to execute a new pending task.

**Find and Execute a New Pending Task**
1.  Find the oldest task with `"status": "pending"`.
2.  If no pending task is found, output "No pending agent tasks to start." and stop.
3.  If a pending task is found, you MUST generate the commands to:
    a. Update the task's status to `"running"`.
    b. Launch the agent as a background process.
    c. **Immediately capture the Process ID (PID)** of the background task using the `$!` shell variable.
    d. **Update the task's JSON file again** to add the captured PID.
    e. Announce that you have started the new task, including its PID.

**Example Execution for task 'task_123' with agent 'coder-agent'**:
```shell
# Step 1: Mark task_123 as running
echo '{"taskId": "task_123", "status": "running", "agent": "coder-agent", ...}' > .gemini/agents/tasks/task_123.json

# Step 2: Execute the agent in the background
gemini -e coder-agent -y -p "You are the coder-agent. Your Task ID is task_123. Your task is to: Write a function. Follow your persona's instructions and create the .done file when finished." >> .gemini/agents/logs/task_123.log 2>&1 &

# Step 3: Capture PID and update the task file again
PID=$!
echo '{"taskId": "task_123", "status": "running", "agent": "coder-agent", "pid": '$PID', ...}' > .gemini/agents/tasks/task_123.json

# Step 4: Announce the start
echo "Orchestrator started task task_123 (PID: $PID) in the background."
```

Now, begin the execution process.
"""